// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzViLfS14U08BJ3m7FrnJdQPVPpu_Jy7E',
    appId: '1:695625482858:web:295a714e96db74f6124013',
    messagingSenderId: '695625482858',
    projectId: 'fir-blood-e155a',
    authDomain: 'fir-blood-e155a.firebaseapp.com',
    storageBucket: 'fir-blood-e155a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbeqH9A-Bum_25QRckp65F-Lqx0nhSU5I',
    appId: '1:695625482858:android:6c00bb8037ebcf1f124013',
    messagingSenderId: '695625482858',
    projectId: 'fir-blood-e155a',
    storageBucket: 'fir-blood-e155a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoy29j8iUNv4FDC3TV5192Xezq-9xsLAQ',
    appId: '1:695625482858:ios:be16b62f39d8ad4b124013',
    messagingSenderId: '695625482858',
    projectId: 'fir-blood-e155a',
    storageBucket: 'fir-blood-e155a.firebasestorage.app',
    iosBundleId: 'com.example.mcpProject',
  );
}
